#pragma once

keys_element_t keys[] =
{ std::make_tuple("none", -1)
, std::make_tuple("escape", 41)
, std::make_tuple("f1", 58)
, std::make_tuple("f2", 59)
, std::make_tuple("f3", 60)
, std::make_tuple("f4", 61)
, std::make_tuple("f5", 62)
, std::make_tuple("f6", 63)
, std::make_tuple("f7", 64)
, std::make_tuple("f8", 65)
, std::make_tuple("f9", 66)
, std::make_tuple("f10", 67)
, std::make_tuple("f11", 68)
, std::make_tuple("f12", 69)
, std::make_tuple("f13", 104)
, std::make_tuple("f14", 105)
, std::make_tuple("f15", 106)
, std::make_tuple("f16", 107)
, std::make_tuple("f17", 108)
, std::make_tuple("f18", 109)
, std::make_tuple("f19", 110)
, std::make_tuple("f20", 111)
, std::make_tuple("f21", 112)
, std::make_tuple("f22", 113)
, std::make_tuple("f23", 114)
, std::make_tuple("f24", 115)
, std::make_tuple("zenkaku/hankaku", 53)
, std::make_tuple("kanji", 53)
, std::make_tuple("tab", 43)
, std::make_tuple("\t", 43)
, std::make_tuple("caps lock", 57)
, std::make_tuple("left shift", 225)
, std::make_tuple("right shift", 229)
, std::make_tuple("shift", 225)
, std::make_tuple("left control", 224)
, std::make_tuple("right control", 228)
, std::make_tuple("control", 224)
, std::make_tuple("left alternate", 226)
, std::make_tuple("left option", 226)
, std::make_tuple("right alternate", 230)
, std::make_tuple("right option", 230)
, std::make_tuple("alternate", 226)
, std::make_tuple("option", 226)
, std::make_tuple("left meta", -2)
, std::make_tuple("right_meta", -3)
, std::make_tuple("meta", -2)
, std::make_tuple("muhenkan", -4)
, std::make_tuple("henkan", -5)
, std::make_tuple("katakana hiragana", -6)
, std::make_tuple("super", -7)
, std::make_tuple("windows", -7)
, std::make_tuple("command", -7)
, std::make_tuple("left windows", -7)
, std::make_tuple("right windows", -8)
, std::make_tuple("menu", 118)
, std::make_tuple("backspace", 187)
, std::make_tuple("enter", 40)
, std::make_tuple("\n", 40)
, std::make_tuple("space", 44)
, std::make_tuple(" ", 44)
, std::make_tuple("1", 30)
, std::make_tuple("2", 31)
, std::make_tuple("3", 32)
, std::make_tuple("4", 33)
, std::make_tuple("5", 34)
, std::make_tuple("6", 35)
, std::make_tuple("7", 36)
, std::make_tuple("8", 37)
, std::make_tuple("9", 38)
, std::make_tuple("0", 39)
, std::make_tuple("a", 4)
, std::make_tuple("b", 5)
, std::make_tuple("c", 6)
, std::make_tuple("d", 7)
, std::make_tuple("e", 8)
, std::make_tuple("f", 9)
, std::make_tuple("g", 10)
, std::make_tuple("h", 11)
, std::make_tuple("i", 12)
, std::make_tuple("j", 13)
, std::make_tuple("k", 14)
, std::make_tuple("l", 15)
, std::make_tuple("m", 16)
, std::make_tuple("n", 17)
, std::make_tuple("o", 18)
, std::make_tuple("p", 19)
, std::make_tuple("q", 20)
, std::make_tuple("r", 21)
, std::make_tuple("s", 22)
, std::make_tuple("t", 23)
, std::make_tuple("u", 24)
, std::make_tuple("v", 25)
, std::make_tuple("w", 26)
, std::make_tuple("x", 27)
, std::make_tuple("y", 28)
, std::make_tuple("z", 29)
, std::make_tuple("minus", 45)
, std::make_tuple("-", 45)
, std::make_tuple("hat", 46)
, std::make_tuple("^", 46)
, std::make_tuple("yen", 49)
, std::make_tuple("\\", 49)
, std::make_tuple("atmark", 47)
, std::make_tuple("@", 47)
, std::make_tuple("left square bracket", 48)
, std::make_tuple("[", 48)
, std::make_tuple("semicolon", 51)
, std::make_tuple(";", 51)
, std::make_tuple("colon", 52)
, std::make_tuple(":", 52)
, std::make_tuple("right square bracket", 49)
, std::make_tuple("]", 49)
, std::make_tuple("comma", 54)
, std::make_tuple(",", 54)
, std::make_tuple("dot", 55)
, std::make_tuple(".", 55)
, std::make_tuple("slash", 56)
, std::make_tuple("/", 56)
, std::make_tuple("backslash", 49)
, std::make_tuple("\\", 49)
, std::make_tuple("print screen", 70)
, std::make_tuple("scroll lock", 71)
, std::make_tuple("pause", 72)
, std::make_tuple("insert", 73)
, std::make_tuple("delete", 76)
, std::make_tuple("home", 74)
, std::make_tuple("end", 77)
, std::make_tuple("page up", 75)
, std::make_tuple("page down", 78)
, std::make_tuple("up", 82)
, std::make_tuple("left", 80)
, std::make_tuple("down", 81)
, std::make_tuple("right", 79)
, std::make_tuple("num lock", 83)
, std::make_tuple("num slash", 84)
, std::make_tuple("num asterisk", 85)
, std::make_tuple("num minus", 86)
, std::make_tuple("num plus", 87)
, std::make_tuple("num enter", 88)
, std::make_tuple("num 7", 95)
, std::make_tuple("num 8", 96)
, std::make_tuple("num 9", 97)
, std::make_tuple("num 4", 92)
, std::make_tuple("num 5", 93)
, std::make_tuple("num 6", 94)
, std::make_tuple("num 1", 89)
, std::make_tuple("num 2", 90)
, std::make_tuple("num 3", 91)
, std::make_tuple("num 0", 98)
, std::make_tuple("num comma", 133)
, std::make_tuple("num dot", 99)
, std::make_tuple("num equal", 103)
, std::make_tuple("num plusminus", -9)
, std::make_tuple("num left paren", 182)
, std::make_tuple("num right paren", 183)
, std::make_tuple("mute", 127)
, std::make_tuple("volume down", 129)
, std::make_tuple("volume up", 128)
, std::make_tuple("power", 102)
, std::make_tuple("sleep", -10)
, std::make_tuple("wake_up", -11)
, std::make_tuple("screen_lock", -12)
, std::make_tuple("www", -13)
, std::make_tuple("mail", -14)
, std::make_tuple("play pause", -15)
, std::make_tuple("next song", -16)
, std::make_tuple("previous song", -17)
, std::make_tuple("wlan", -18)
, std::make_tuple("bluetooth", -19)
, std::make_tuple("brightness down", -20)
, std::make_tuple("brightness up", -21)
, std::make_tuple("display off", -22)
, std::make_tuple("function", -2)
};
